### ISSUE TITLE
PlayerEx Mod 引起崩溃

### ISSUE THREAD

**Issue by Puqns67** [BrokenDawn627/Infinity-Modpack#10]
[崩溃日志](https://github.com/BrokenDawn627/Infinity-Modpack/files/8499725/CrashLogs.zip)
Mod 出现问题后被 WatchDog 杀掉
![image](https://user-images.githubusercontent.com/57405236/163672045-67f217fa-c715-49ff-b5c4-23e09bd28286.png)

**Comment by BrokenDawn627** [comment]
老问题了 很久之前就和模组作者反馈了 但是作者还在鸽

**Comment by Puqns67** [comment]
有没有什么缓解的办法啊，十几分钟崩一次实在是绷不住了

**Comment by BrokenDawn627** [comment]
正常应该不会出现连续崩的情况 可以尝试更新下整合包或者在游戏内换个区域发展
