### ISSUE TITLE
精英怪反甲

### ISSUE THREAD

**Issue by AkumaLeo** [BrokenDawn627/Infinity-Modpack#11]
玩家攻击带有反甲字缀精英怪，被伤害反弹死亡，有概率不生成墓碑。
另外部分带装备的僵尸攻击死亡也会导致不生成墓碑，不知是否是真伤造成

**Comment by BrokenDawn627** [comment]
如果死亡左下角聊天框会出死亡提示 就应该会出现墓碑 刚刚群里问了一下似乎没有人在最新版本遇到过被反甲反死导致的墓碑丢失

**Comment by BrokenDawn627** [comment]
最新版本已经移除了真伤 此问题应不再发生
