### ISSUE TITLE
服务器连续崩溃。。

### ISSUE THREAD

**Issue by ew8** [BrokenDawn627/Infinity-Modpack#15]
[2022-04-20-7.log.gz](https://github.com/BrokenDawn627/Infinity-Modpack/files/8520427/2022-04-20-7.log.gz)
[crash-2022-04-20_17.43.50-server.txt](https://github.com/BrokenDawn627/Infinity-Modpack/files/8520429/crash-2022-04-20_17.43.50-server.txt)
第一个是运行log(latest) 第二个是崩溃报告，
服务器崩溃的很频繁，并且错误都一样,都是说凋零骷髅报错，且每次坐标不一样。
劳烦帮忙看一下，谢谢
（btw整合包质量不错的说，群里的肝帝已经好几天没睡觉了）

**Comment by BrokenDawn627** [comment]
切换难度为和平 把怪刷掉 然后更新整合包和服务端到最新版本 看看是否还会出现问题

**Comment by ew8** [comment]
hmm稳定了几天的确没问题了。。。真是奇怪。。。
