### ISSUE TITLE
死亡闪退 然后没有生成坟墓

### ISSUE THREAD

**Issue by MRailgun** [BrokenDawn627/Infinity-Modpack#2]
以下为multimc的报错报告，
[log.txt](https://github.com/BrokenDawn627/Infinity-Modpack/files/8077570/log.txt)

**Comment by MRailgun** [comment]
游戏版本为Beta11-pre2

**Comment by BrokenDawn627** [comment]
已和模组作者反馈

**Comment by MRailgun** [comment]
是哪个mod导致的

**Comment by BrokenDawn627** [comment]
请重装you are in grave danger 模组 这是由于json文件缺失导致的 模组作者是这么回复的

**Comment by Makarexe** [comment]
Please translate the text in the initial book into English
