### ISSUE TITLE
客户端进入服务器崩溃

### ISSUE THREAD

**Issue by AweiDev** [BrokenDawn627/Infinity-Modpack#21]
进入服务器时崩溃，使用CurseForge上托管包 PCL下载 
服务器包也是托管包下载
未动过任何mod配置等
crash-2022-05-09_17.04.39-client.txt :"https://pastebin.ubuntu.com/p/BgwKQHTMfd/"
latest.log :"https://pastebin.ubuntu.com/p/T66FGTdfgm/"

**Comment by AweiDev** [comment]
我看了，好像是注册的维度问题

**Comment by BrokenDawn627** [comment]
由于天境模组导致的崩溃 另外pcl没有完整性检查 会导致模组缺失 请使用其他启动器

**Comment by AweiDev** [comment]
好的，我使用其他的启动器

**Comment by AweiDev** [comment]
还是不行，使用了HMCL重新安装依旧崩溃
这个是HMCL的报
latest.log : "https://pastebin.ubuntu.com/p/hPBjbCHG9g/"
告

**Comment by AweiDev** [comment]
我试图禁用了InventoryHUD+
但是依旧崩溃

**Comment by BrokenDawn627** [comment]
详细描述下崩溃前干了什么

**Comment by BrokenDawn627** [comment]
另外请确保下载的服务端版本与客户端版本一致

**Comment by AweiDev** [comment]
崩溃前
1.使用HMCL启动客户端
2.选择JDK17
3.启动游戏
4.选择多人服务器
5.进入服务器
6.出现加入游戏后变成了保存游戏中（崩溃）
未更改任何东西
CurerForge下载服务包
版本一致

**Comment by AweiDev** [comment]
服务器包名：Server-Infinity-Beta20-HotFix.zip
客户端包名：Infinity-Beta20-HotFix.zip
版本都是Beta20

**Comment by AweiDev** [comment]
我在看日志latest.log发现了渲染错误 [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot read field "field_13073" because "$$0" is null
我试图删除options.txt来解决这个问题，修复了崩溃，但是无法进入服务器了
返回信息是 无 
服务器后台是没有任何信息
