### ISSUE TITLE
您好用召唤师附魔召唤出来的僵尸猪灵打死精英怪不给附魔书么？这是不是个BUG还是就是这么设定的

### ISSUE THREAD

**Issue by lzyhljm** [BrokenDawn627/Infinity-Modpack#24]
您好用召唤师附魔召唤出来的僵尸猪灵打死精英怪不给附魔书么？这是不是个BUG还是就是这么设定的

**Comment by BrokenDawn627** [comment]
仅玩家击杀会掉落

**Comment by lzyhljm** [comment]
请问怎么样单独去除其中一个附魔




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BrokenDawn627/Infinity-Modpack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BrokenDawn627/Infinity-Modpack] 您好用召唤师附魔召唤出来的僵尸猪灵打死精英怪不给附魔书么？这是不是个BUG还是就是这么设定的 (Issue #24)





 
仅玩家击杀会掉落
