### ISSUE TITLE
几个附魔的漏洞（召唤师，破晓）

### ISSUE THREAD

**Issue by lcy0x1** [BrokenDawn627/Infinity-Modpack#26]
1. 召唤师刷出来的猪人能打死，同时有概率出精英怪，导致能用召唤师做猪人塔，安全刷级的同时获取大量资源
2. +12以上的武器破晓突破成功会变成+1996的调试棒，配上好的附魔能dps超过60000，秒杀所有boss

**Comment by BrokenDawn627** [comment]
很好 之后全ban了
