### ISSUE TITLE
The discord invite link on curseforge is expired

### ISSUE THREAD

**Issue by hurui200320** [BrokenDawn627/Infinity-Modpack#27]
The current discord invite link listed on the curseforge page is https://discord.com/invite/7gYRz2ty

Which is expired (reported by discord). Please replace it with a validated one :)

**Comment by hurui200320** [comment]
Out of context: It would be nice to have a Patreon donate link.

**Comment by BrokenDawn627** [comment]
I have replaced it. Thanks for reminding.
已经换了，感谢提醒，还有我不理解为啥发英文。
现在暂时没有打算搞Patreon赞助 赞助都在爱发电

**Comment by hurui200320** [comment]
我看仓库的readme是英文，就发了个英文issue（
