### ISSUE TITLE
可能是与replay mod不兼容？

### ISSUE THREAD

**Issue by xiamiemie** [BrokenDawn627/Infinity-Modpack#28]
大大你好，我用的是5月29号在curseforge桌面客户端下载的模组，是想录制游玩视频。去https://www.replaymod.com/下载了对应1.18版本的mod，在游戏过程中录制并没有问题，但是保存退回登录界面之后没有replay功能里的回放和编辑按钮，无法查看和编辑录制好的视频。

**Comment by BrokenDawn627** [comment]
需要下载与sodium兼容的replaymod版本
