### ISSUE TITLE
beta12 无论服务端还是直接局域网联机 玩着玩着就崩溃了

### ISSUE THREAD

**Issue by shihuaizg** [BrokenDawn627/Infinity-Modpack#3]
![image](https://user-images.githubusercontent.com/80575079/154570198-62f982c6-67b2-414e-b909-5568893b712a.png)
![image](https://user-images.githubusercontent.com/80575079/154570142-f5b72e7a-0b60-4537-94e6-cf70898ff3b3.png)
经常出现这种崩溃，服务端里 存档里玩都是这样的情况 崩了重开后没一会又会崩
forge能在fogre.cfg里打开自动清理错误实体的功能，但是fabric不知道有没有
以下为日志
[crash-2022-02-18_01.48.11-server.txt](https://github.com/BrokenDawn627/Infinity-Modpack/files/8092195/crash-2022-02-18_01.48.11-server.txt)
[latest.log](https://github.com/BrokenDawn627/Infinity-Modpack/files/8092196/latest.log)
[2022-02-18-6.log](https://github.com/BrokenDawn627/Infinity-Modpack/files/8092206/2022-02-18-6.log)

**Comment by BrokenDawn627** [comment]
稍后会发布Beta12热修复版本 请尝试更新后是否仍会出现该问题

**Comment by BrokenDawn627** [comment]
似乎问题还是没有解决 要不可以先玩beta11-pre2

**Comment by shihuaizg** [comment]
今天跟朋友开服玩了一天确实没遇到什么bug了 也没有崩一次
建议增加以下mod让游戏体验更好🤔
[IMBlockerFabric【游戏里不用切英文输入法】](https://www.mcmod.cn/class/2840.html)
 [megane【显示容器内物品、流体、烧制时间】](https://www.mcmod.cn/class/4511.html
)
[cimtb【手持工具挖掘能否掉落】](https://www.mcmod.cn/class/3084.html
)
[DashLoader【能让游戏启动加快】](https://www.mcmod.cn/class/3841.html)
