### ISSUE TITLE
局域网联机经常崩溃，并回档

### ISSUE THREAD

**Issue by yanlingww** [BrokenDawn627/Infinity-Modpack#38]
[minecraft-exported-logs-2022-06-20T11-33-58.log](https://github.com/BrokenDawn627/Infinity-Modpack/files/8938134/minecraft-exported-logs-2022-06-20T11-33-58.log)

**Comment by BrokenDawn627** [comment]
https://github.com/CleverNucleus/PlayerEx/issues/50
