### ISSUE TITLE
平衡问题

### ISSUE THREAD

**Issue by Akidofiwanna** [BrokenDawn627/Infinity-Modpack#7]
植魔附魔台，祛魔台，破晓附魔共同引起了这个问题
植魔附魔台不消耗书，且可以附超过正常上限的附魔（例如锋利6，而铁砧不行）
破晓可以突破附魔上限
祛魔台可以把突破附魔上限的附魔摘下来
然后植魔再附魔回去可以再次破晓，导致附魔可以无上限的叠加
然后就有了，光环药水抗性提升V（抵抗100%伤害）
饵钓V，海神之眷X，图书管理员X，附魔书随便钓
每三次攻击附带100%生命上限的真实伤害（忘记叫什么附魔了，3刀任意秒）

**Comment by BrokenDawn627** [comment]
已收到反馈 请等待后续版本进行平衡性调整
