### ISSUE TITLE
打开背包箱子掉帧

### ISSUE THREAD

**Issue by Yuesikui** [BrokenDawn627/Infinity-Modpack#8]
正常游玩是50帧，打开背包箱子直接16帧左右
没用错误报告
![屏幕截图 2022-04-14 123544](https://user-images.githubusercontent.com/103621672/163314501-e33b9b43-2c74-459d-b8af-3266474c3eb9.png)

**Comment by BrokenDawn627** [comment]
安装了动态FPS模组 可能是由于切出窗口导致掉帧

**Comment by Yuesikui** [comment]
禁用了，没有效果

**Comment by xiaxin113** [comment]
删除blur模组

**Comment by Yuesikui** [comment]
![image](https://user-images.githubusercontent.com/103621672/165324623-2845ca29-c222-45c7-8ba2-04c62afa8480.png)
![屏幕截图 2022-04-26 223415](https://user-images.githubusercontent.com/103621672/165324641-53106853-cb0c-4681-a145-8e72c04da380.png)

**Comment by Yuesikui** [comment]
主要是没有bug反馈，掉帧就挺难受的

**Comment by BrokenDawn627** [comment]
把x-hp模组禁用了试试呢

**Comment by Yuesikui** [comment]
刚刚试了没有效果

**Comment by BrokenDawn627** [comment]
或者Ctrl+O隐藏REI界面试试
