### ISSUE TITLE
Beta 17 崩溃

### ISSUE THREAD

**Issue by Puqns67** [BrokenDawn627/Infinity-Modpack#9]
Beta 17 崩溃，大概是词缀引起的，[这是日志](https://github.com/BrokenDawn627/Infinity-Modpack/files/8495753/logs.zip)
![image](https://user-images.githubusercontent.com/57405236/163567790-23f7c2b3-7e2a-4060-a086-259482eeeadb.png)

**Comment by BrokenDawn627** [comment]
见热修版或热修补丁 更新后如果仍崩溃再说

**Comment by Puqns67** [comment]
[这里](https://github.com/BrokenDawn627/Infinity-Modpack/blob/39d8e46be3e422e53b3be99b3e03c6d79cea4c88/kubejs/server_scripts/difficulty.js#L314-L359)还有个问题，player.stages 有可能为 null，所以应该加个 if (player.stages != null) 给他套上，或者给他把状态还原了，出现这句 log 后服务端直接卡死，强杀都杀不掉，不知道是不是就是这个引起的，[Kubejs日志](https://github.com/BrokenDawn627/Infinity-Modpack/files/8497034/logs.zip)
![image](https://user-images.githubusercontent.com/57405236/163597785-f2939db4-87a7-4efb-a3d9-a344d3de29c0.png)

**Comment by Puqns67** [comment]
> [这里](https://github.com/BrokenDawn627/Infinity-Modpack/blob/39d8e46be3e422e53b3be99b3e03c6d79cea4c88/kubejs/server_scripts/difficulty.js#L314-L359)还有个问题，player.stages 有可能为 null，所以应该加个 if (player.stages != null) 给他套上，或者给他把状态还原了，出现这句 log 后服务端直接卡死，强杀都杀不掉，不知道是不是就是这个引起的，[Kubejs日志](https://github.com/BrokenDawn627/Infinity-Modpack/files/8497034/logs.zip) ![image](https://user-images.githubusercontent.com/57405236/163597785-f2939db4-87a7-4efb-a3d9-a344d3de29c0.png)

我这里用的是 Beta 16，如果 Beta 17 修复了那当我没说，Beta 17 的词条出现高级怪的概率是否有点太高了，大部分都是四五个词条，有点恐怖，暂时不打算升了 QwQ

**Comment by Puqns67** [comment]
此问题应该已修正
